# Generated by Django 6.0.4 on 2026-04-11 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DAILY', '일간'), ('WEEKLY', '주간'), ('MONTHLY', '월간'), ('YEARLY', '연간')], default='DAILY', max_length=10)),
                ('about', models.CharField(choices=[('TOTAL_SPENDING', '총 지출'), ('TOTAL_INCOME', '총 수입')], default='TOTAL_SPENDING', max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('description', models.TextField()),
                ('result_image', models.ImageField(default='analysis/default.png', upload_to='analysis/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
