# Generated by Django 6.0.3 on 2026-04-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '입금'), ('WITHDRAW', '출금')], default='DEPOSIT', max_length=20)),
                ('transaction_method', models.CharField(choices=[('ATM', 'ATM 거래'), ('TRANSFER', '계좌이체'), ('AUTOMATIC_TRANSFER', '자동이체'), ('CARD', '카드결제'), ('INTEREST', '이자')], default='ATM', max_length=20)),
                ('balance_after', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account'], name='transaction_account_36745c_idx'), models.Index(fields=['transaction_type', 'transaction_amount', 'transaction_method'], name='transaction_transac_850ddf_idx'), models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx')],
            },
        ),
    ]
